name: Trigger Action on Main Branch Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run your custom action
      run: |
        curl -X GET https://yoursite.com/wp-json/custom/v1/trigger-action/
